/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SpenderERC20Approval__factory } from './SpenderERC20Approval__factory';
export { WETH__factory } from './WETH__factory';
