/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { SpenderERC20Approval, SpenderERC20ApprovalInterface } from '../SpenderERC20Approval';

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: 'token',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'pullToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address[]',
        name: 'tokens',
        type: 'address[]',
      },
      {
        internalType: 'uint256[]',
        name: 'amounts',
        type: 'uint256[]',
      },
    ],
    name: 'pullTokens',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;

export class SpenderERC20Approval__factory {
  static readonly abi = _abi;
  static createInterface(): SpenderERC20ApprovalInterface {
    return new utils.Interface(_abi) as SpenderERC20ApprovalInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): SpenderERC20Approval {
    return new Contract(address, _abi, signerOrProvider) as SpenderERC20Approval;
  }
}
