/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Comptroller__factory } from './Comptroller__factory';
export { CErc20Immutable__factory } from './CErc20Immutable__factory';
