/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Permit2 } from './Permit2';
export type { SpenderPermit2ERC20 } from './SpenderPermit2ERC20';
export * as factories from './factories';
export { Permit2__factory } from './factories/Permit2__factory';
export { SpenderPermit2ERC20__factory } from './factories/SpenderPermit2ERC20__factory';
