/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Permit2__factory } from './Permit2__factory';
export { SpenderPermit2ERC20__factory } from './SpenderPermit2ERC20__factory';
