/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from './common';

export interface MorphoFlashLoanCallbackInterface extends utils.Interface {
  functions: {
    'feeRate()': FunctionFragment;
    'flashLoan(address,uint256,bytes)': FunctionFragment;
    'metadata()': FunctionFragment;
    'morpho()': FunctionFragment;
    'onMorphoFlashLoan(uint256,bytes)': FunctionFragment;
    'router()': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: 'feeRate' | 'flashLoan' | 'metadata' | 'morpho' | 'onMorphoFlashLoan' | 'router'
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'feeRate', values?: undefined): string;
  encodeFunctionData(functionFragment: 'flashLoan', values: [string, BigNumberish, BytesLike]): string;
  encodeFunctionData(functionFragment: 'metadata', values?: undefined): string;
  encodeFunctionData(functionFragment: 'morpho', values?: undefined): string;
  encodeFunctionData(functionFragment: 'onMorphoFlashLoan', values: [BigNumberish, BytesLike]): string;
  encodeFunctionData(functionFragment: 'router', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'feeRate', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'flashLoan', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'metadata', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'morpho', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'onMorphoFlashLoan', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'router', data: BytesLike): Result;

  events: {};
}

export interface MorphoFlashLoanCallback extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MorphoFlashLoanCallbackInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    feeRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    flashLoan(
      token: string,
      assets: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    metadata(overrides?: CallOverrides): Promise<[string]>;

    morpho(overrides?: CallOverrides): Promise<[string]>;

    onMorphoFlashLoan(
      assets: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    router(overrides?: CallOverrides): Promise<[string]>;
  };

  feeRate(overrides?: CallOverrides): Promise<BigNumber>;

  flashLoan(
    token: string,
    assets: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  metadata(overrides?: CallOverrides): Promise<string>;

  morpho(overrides?: CallOverrides): Promise<string>;

  onMorphoFlashLoan(
    assets: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  router(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    feeRate(overrides?: CallOverrides): Promise<BigNumber>;

    flashLoan(token: string, assets: BigNumberish, data: BytesLike, overrides?: CallOverrides): Promise<void>;

    metadata(overrides?: CallOverrides): Promise<string>;

    morpho(overrides?: CallOverrides): Promise<string>;

    onMorphoFlashLoan(assets: BigNumberish, data: BytesLike, overrides?: CallOverrides): Promise<void>;

    router(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    feeRate(overrides?: CallOverrides): Promise<BigNumber>;

    flashLoan(
      token: string,
      assets: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    metadata(overrides?: CallOverrides): Promise<BigNumber>;

    morpho(overrides?: CallOverrides): Promise<BigNumber>;

    onMorphoFlashLoan(
      assets: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    router(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    feeRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    flashLoan(
      token: string,
      assets: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    metadata(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    morpho(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onMorphoFlashLoan(
      assets: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    router(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
