/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { ProtocolFeesCollector, ProtocolFeesCollectorInterface } from '../ProtocolFeesCollector';

const _abi = [
  {
    inputs: [],
    name: 'getFlashLoanFeePercentage',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export class ProtocolFeesCollector__factory {
  static readonly abi = _abi;
  static createInterface(): ProtocolFeesCollectorInterface {
    return new utils.Interface(_abi) as ProtocolFeesCollectorInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ProtocolFeesCollector {
    return new Contract(address, _abi, signerOrProvider) as ProtocolFeesCollector;
  }
}
